remote: True

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: false
  contract: false
  part-time: true
  temporary: true
  internship: true
  other: true
  volunteer: true

date:
  all time: false
  month: true
  week: false
  24 hours: true

positions:
  - Software Developer
  - Data Scientist

locations:
  - USA
  - Germany
  
distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist: []
